export interface Employee {
  id: string; // UUID generated by supabase.

  employee_id: string; // human-friendly id like EMP001.

  full_name: string; // employee full name.

  email: string; // login email.

  phone: string | null;

  department: string | null;

  designation: string | null;

  role: string;

  avatar_url: string | null;

  status: string;

  is_online: boolean;

  last_login: string | null;

  joined_date: string | null;

  date_of_birth: string | null;

  current_address: string | null;

  qualification: string | null;

  degree: string | null;

  experience_years: number | null;

  emergency_contact: string | null;

  created_at: string;

  updated_at: string | null;
}

export interface EmployeeOnboardingResult {
  employeeId: string;
  credentials: EmployeeCredentials;
}

export interface EmployeeCredentials {
  fullName: string;
  email: string;
  password: string;
  portalUrl: string;
}
